openapi: 3.0.3
info:
  title: Enterprise User Management API
  description: API for managing user accounts, including creation, retrieval, updates, and audit logs.
  version: 1.0.0
servers:
  - url: /api/users
    description: Base path for User resources

tags:
  - name: Users
    description: Core User CRUD and profile management
  - name: Security
    description: Operations related to user security (password change)

paths:
  /users/:
    post:
      tags:
        - Users
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid request or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      tags:
        - Users
      summary: Get a paginated list of all users (Admin only)
      operationId: getAllUsers
      security:
        - bearerAuth: [ROLE_ADMIN]
      parameters:
        - $ref: '#/components/parameters/PageParameter'
        - $ref: '#/components/parameters/SizeParameter'
        - $ref: '#/components/parameters/SortParameter'
      responses:
        '200':
          description: A paginated list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfUserResponse'
        '403':
          description: Forbidden (Requires ROLE_ADMIN)

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user details by ID
      operationId: getUserById
      security:
        - bearerAuth: [ROLE_USER]
      parameters:
        - in: path
          name: id
          description: ID of the user to retrieve
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/RequesterIdHeader'
      responses:
        '200':
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: User not found
    put:
      tags:
        - Users
      summary: Update existing user details
      operationId: updateUser
      security:
        - bearerAuth: [ROLE_USER]
      parameters:
        - in: path
          name: id
          description: ID of the user to update
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/RequesterIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '403':
          description: Forbidden (Cannot update another user's profile unless Admin)
        '404':
          description: User not found
    delete:
      tags:
        - Users
      summary: Delete a user by ID (Admin only)
      operationId: deleteUser
      security:
        - bearerAuth: [ROLE_ADMIN]
      parameters:
        - in: path
          name: id
          description: ID of the user to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully (No Content)
        '403':
          description: Forbidden (Requires ROLE_ADMIN)
        '404':
          description: User not found

  /users/username/{username}:
    get:
      tags:
        - Users
      summary: Get user details by username
      operationId: getUserByUsername
      parameters:
        - in: path
          name: username
          description: Username of the user to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: User not found

  /users/{id}/password:
    patch:
      tags:
        - Security
      summary: Change user's password
      operationId: changePassword
      security:
        - bearerAuth: [ROLE_USER]
      parameters:
        - in: path
          name: id
          description: ID of the user whose password is being changed
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/RequesterIdHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '403':
          description: Forbidden (Cannot change another user's password)

  /users/{id}/audit-logs:
    get:
      tags:
        - Users
      summary: Get user-specific audit logs
      operationId: getUserAuditLogs
      security:
        - bearerAuth: [ROLE_USER]
      parameters:
        - in: path
          name: id
          description: ID of the user whose audit logs are being requested
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/RequesterIdHeader'
        - $ref: '#/components/parameters/PageParameter'
        - $ref: '#/components/parameters/SizeParameter'
        - $ref: '#/components/parameters/SortParameter'
      responses:
        '200':
          description: Paginated audit logs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAuditLogResponse'
        '403':
          description: Forbidden (Cannot view another user's logs)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    RequesterIdHeader:
      in: header
      name: X-User-Id
      description: The ID of the authenticated user making the request (for authorization checks).
      required: true
      schema:
        type: string
    PageParameter:
      in: query
      name: page
      schema:
        type: integer
        default: 0
      description: Zero-based page index.
    SizeParameter:
      in: query
      name: size
      schema:
        type: integer
        default: 20
      description: The size of the page to be returned.
    SortParameter:
      in: query
      name: sort
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
      description: 'Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria can be used (e.g., sort=name,desc&sort=id,asc).'

  schemas:
    # --- Request Schemas ---
    CreateUserRequest:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
        password:
          type: string
          format: password
          minLength: 12
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        roles:
          type: array
          items:
            type: string

    UpdateUserRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
          format: email

    ChangePasswordRequest:
      type: object
      required:
        - currentPassword
        - newPassword
      properties:
        currentPassword:
          type: string
          format: password
        newPassword:
          type: string
          format: password
          minLength: 12

    # --- Response Schemas ---
    UserResponse:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        roles:
          type: array
          items:
            type: string
        enabled:
          type: boolean
        lastLogin:
          type: string
          format: date-time # Maps to Java's Instant
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    AuditLogResponse:
      type: object
      properties:
        id:
          type: string
        action:
          type: string
        entityType:
          type: string
        entityId:
          type: string
        details:
          type: string
        timestamp:
          type: string
          format: date-time
        success:
          type: boolean

    MessageResponse:
      type: object
      properties:
        message:
          type: string

    # --- Pageable Response Schemas (Spring Data specific) ---
    PageOfUserResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        totalPages:
          type: integer
        totalElements:
          type: integer
        last:
          type: boolean
        size:
          type: integer
        number:
          type: integer
        first:
          type: boolean
        numberOfElements:
          type: integer
        empty:
          type: boolean

    PageOfAuditLogResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/AuditLogResponse'
        totalPages:
          type: integer
        totalElements:
          type: integer
        last:
          type: boolean
        size:
          type: integer
        number:
          type: integer
        first:
          type: boolean
        numberOfElements:
          type: integer
        empty:
          type: boolean

    UserAuthInfo:
      type: object
      description: Internal DTO for user authentication and authorization information.
      properties:
        id:
          type: string
          description: Unique identifier of the user.
        username:
          type: string
          description: User's chosen username.
        password:
          type: string
          format: password # Indicates sensitive data that should be hidden/masked.
          description: Hashed password (should not be exposed in public APIs).
        roles:
          type: array
          description: Set of roles assigned to the user (e.g., 'ROLE_USER', 'ROLE_ADMIN').
          items:
            type: string
        enabled:
          type: boolean
          description: Indicates whether the user account is active/enabled.

    ErrorResponse:
      type: object
      description: Standard error response
      # @JsonInclude(JsonInclude.Include.NON_NULL) implies properties might be omitted if null,
      # so we do not list all fields under 'required' by default.
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the error occurred
          # @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss") suggests a specific format
          example: 2024-01-15T10:30:00

        status:
          type: integer
          format: int32
          description: HTTP status code
          example: 400

        errorCode:
          type: string
          description: Error code for client-side handling
          example: VALIDATION_ERROR

        message:
          type: string
          description: Human-readable error message
          example: Validation failed

        details:
          type: string
          description: Detailed error description

        path:
          type: string
          description: Request path that caused the error
          example: /api/users

        fieldErrors:
          type: array
          description: Validation errors (field-level)
          items:
            $ref: '#/components/schemas/FieldError'

        metadata:
          type: object
          description: Additional error metadata
          # Use additionalProperties to allow arbitrary key/value pairs
          additionalProperties: { }

        correlationId:
          type: string
          description: Correlation ID for tracing
          example: 550e8400-e29b-41d4-a716-446655440000
    FieldError:
      type: object
      description: Field-level validation error
      properties:
        field:
          type: string
          description: Field name
          example: email

        rejectedValue:
          # Use 'object' to match Java's 'Object' type for flexibility
          type: object
          description: Rejected value
          example: invalid-email

        message:
          type: string
          description: Error message
          example: must be a well-formed email address

        constraint:
          type: string
          description: Validation constraint
          example: Email